
name: Python cash app

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, Faizan, Danyal]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.16

    - name: Install dependencies
      run: |
        make install

#     - name: Linting
#       run: |
#         make lint

    - name: Testing
      run: |
        make test

    - name: Invoking
      run: |
        make invoke

    - name: running-kube
      run: |
        make run-kube

       
